/* -------------------------------------------------------------------------- */
/* PHONE & PROPERTY TYPES                           */
/* -------------------------------------------------------------------------- */

export const PHONE_TYPES = [
  { code: '1', label: 'Voice' },
  { code: '3', label: 'Fax' },
  { code: '5', label: 'Mobile' },
];

export const PROPERTY_TYPES = [
  { code: '1', label: 'Hotel' },
  { code: '2', label: 'Motel' },
  { code: '3', label: 'Vacation Rental' },
];

/* -------------------------------------------------------------------------- */
/* LANGUAGES                                 */
/* -------------------------------------------------------------------------- */

export const LANGUAGES = [
  { code: 'en', label: 'English (UK)' },
  { code: 'en-us', label: 'English (American)' },
  { code: 'ar', label: 'Arabic' },
  { code: 'az', label: 'Azerbaijani' },
  { code: 'bg', label: 'Bulgarian' },
  { code: 'ca', label: 'Catalan' },
  { code: 'xt', label: 'Chinese (Cantonese)' },
  { code: 'zh', label: 'Chinese (Mandarin)' },
  { code: 'zh-cn', label: 'Chinese (Simplified)' },
  { code: 'zh-tw', label: 'Chinese (Traditional)' },
  { code: 'hr', label: 'Croatian' },
  { code: 'cs', label: 'Czech' },
  { code: 'da', label: 'Danish' },
  { code: 'nl', label: 'Dutch' },
  { code: 'et', label: 'Estonian' },
  { code: 'fi', label: 'Finnish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'el', label: 'Greek' },
  { code: 'he', label: 'Hebrew' },
  { code: 'hi', label: 'Hindi' },
  { code: 'hu', label: 'Hungarian' },
  { code: 'is', label: 'Icelandic' },
  { code: 'id', label: 'Indonesian' },
  { code: 'it', label: 'Italian' },
  { code: 'ja', label: 'Japanese' },
  { code: 'km', label: 'Khmer' },
  { code: 'ko', label: 'Korean' },
  { code: 'lo', label: 'Lao' },
  { code: 'lv', label: 'Latvian' },
  { code: 'lt', label: 'Lithuanian' },
  { code: 'ms', label: 'Malay' },
  { code: 'no', label: 'Norwegian' },
  { code: 'pl', label: 'Polish' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'pt-br', label: 'Portuguese (Brazilian)' },
  { code: 'ro', label: 'Romanian' },
  { code: 'ru', label: 'Russian' },
  { code: 'sr', label: 'Serbian' },
  { code: 'sk', label: 'Slovak' },
  { code: 'sl', label: 'Slovenian' },
  { code: 'es', label: 'Spanish' },
  { code: 'es-ar', label: 'Spanish (Argentine)' },
  { code: 'xs', label: 'Spanish (South American)' },
  { code: 'sv', label: 'Swedish' },
  { code: 'tl', label: 'Tagalog' },
  { code: 'th', label: 'Thai' },
  { code: 'tr', label: 'Turkish' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'vi', label: 'Vietnamese' },
];

/* -------------------------------------------------------------------------- */
/* CURRENCIES                                 */
/* -------------------------------------------------------------------------- */

export const CURRENCIES = [
  { code: 'USD', label: 'United States Dollar' },
  { code: 'GBP', label: 'British Pound Sterling' },
  { code: 'EUR', label: 'Euro' },
  { code: 'AED', label: 'United Arab Emirates Dirham' },
  { code: 'AFN', label: 'Afghan Afghani' },
  { code: 'ALL', label: 'Albanian Lek' },
  { code: 'AMD', label: 'Armenian Dram' },
  { code: 'ANG', label: 'Netherlands Antillean Guilder' },
  { code: 'AOA', label: 'Angolan Kwanza' },
  { code: 'ARS', label: 'Argentine Peso' },
  { code: 'AUD', label: 'Australian Dollar' },
  { code: 'AWG', label: 'Aruban Florin' },
  { code: 'AZN', label: 'Azerbaijani Manat' },
  { code: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark' },
  { code: 'BBD', label: 'Barbadian Dollar' },
  { code: 'BDT', label: 'Bangladeshi Taka' },
  { code: 'BGN', label: 'Bulgarian Lev' },
  { code: 'BHD', label: 'Bahraini Dinar' },
  { code: 'BIF', label: 'Burundian Franc' },
  { code: 'BMD', label: 'Bermudan Dollar' },
  { code: 'BND', label: 'Brunei Dollar' },
  { code: 'BOB', label: 'Bolivian Boliviano' },
  { code: 'BRL', label: 'Brazilian Real' },
  { code: 'BSD', label: 'Bahamian Dollar' },
  { code: 'BTN', label: 'Bhutanese Ngultrum' },
  { code: 'BWP', label: 'Botswanan Pula' },
  { code: 'BYR', label: 'Belarusian Ruble' },
  { code: 'BZD', label: 'Belize Dollar' },
  { code: 'CAD', label: 'Canadian Dollar' },
  { code: 'CDF', label: 'Congolese Franc' },
  { code: 'CHF', label: 'Swiss Franc' },
  { code: 'CLP', label: 'Chilean Peso' },
  { code: 'CNY', label: 'Chinese Yuan' },
  { code: 'COP', label: 'Colombian Peso' },
  { code: 'CRC', label: 'Costa Rican Colón' },
  { code: 'CUP', label: 'Cuban Peso' },
  { code: 'CVE', label: 'Cape Verdean Escudo' },
  { code: 'CZK', label: 'Czech Republic Koruna' },
  { code: 'DJF', label: 'Djiboutian Franc' },
  { code: 'DKK', label: 'Danish Krone' },
  { code: 'DOP', label: 'Dominican Peso' },
  { code: 'DZD', label: 'Algerian Dinar' },
  { code: 'EGP', label: 'Egyptian Pound' },
  { code: 'ERN', label: 'Eritrean Nakfa' },
  { code: 'ETB', label: 'Ethiopian Birr' },
  { code: 'FJD', label: 'Fijian Dollar' },
  { code: 'FKP', label: 'Falkland Islands Pound' },
  { code: 'GEL', label: 'Georgian Lari' },
  { code: 'GGP', label: 'Guernsey Pound' },
  { code: 'GHS', label: 'Ghanaian Cedi' },
  { code: 'GIP', label: 'Gibraltar Pound' },
  { code: 'GMD', label: 'Gambian Dalasi' },
  { code: 'GNF', label: 'Guinean Franc' },
  { code: 'GTQ', label: 'Guatemalan Quetzal' },
  { code: 'GYD', label: 'Guyanaese Dollar' },
  { code: 'HKD', label: 'Hong Kong Dollar' },
  { code: 'HNL', label: 'Honduran Lempira' },
  { code: 'HRK', label: 'Croatian Kuna' },
  { code: 'HTG', label: 'Haitian Gourde' },
  { code: 'HUF', label: 'Hungarian Forint' },
  { code: 'IDR', label: 'Indonesian Rupiah' },
  { code: 'ILS', label: 'Israeli New Sheqel' },
  { code: 'IMP', label: 'Manx pound' },
  { code: 'INR', label: 'Indian Rupee' },
  { code: 'IQD', label: 'Iraqi Dinar' },
  { code: 'IRR', label: 'Iranian Rial' },
  { code: 'JMD', label: 'Jamaican Dollar' },
  { code: 'JOD', label: 'Jordanian Dinar' },
  { code: 'JPY', label: 'Japanese Yen' },
  { code: 'KES', label: 'Kenyan Shilling' },
  { code: 'KGS', label: 'Kyrgystani Som' },
  { code: 'KHR', label: 'Cambodian Riel' },
  { code: 'KMF', label: 'Comorian Franc' },
  { code: 'KPW', label: 'North Korean Won' },
  { code: 'KRW', label: 'South Korean Won' },
  { code: 'KWD', label: 'Kuwaiti Dinar' },
  { code: 'KYD', label: 'Cayman Islands Dollar' },
  { code: 'KZT', label: 'Kazakhstani Tenge' },
  { code: 'LAK', label: 'Laotian Kip' },
  { code: 'LBP', label: 'Lebanese Pound' },
  { code: 'LKR', label: 'Sri Lankan Rupee' },
  { code: 'LRD', label: 'Liberian Dollar' },
  { code: 'LSL', label: 'Lesotho Loti' },
  { code: 'LTL', label: 'Lithuanian Litas' },
  { code: 'LVL', label: 'Latvian Lats' },
  { code: 'LYD', label: 'Libyan Dinar' },
  { code: 'MAD', label: 'Moroccan Dirham' },
  { code: 'MDL', label: 'Moldovan Leu' },
  { code: 'MGA', label: 'Malagasy Ariary' },
  { code: 'MKD', label: 'Macedonian Denar' },
  { code: 'MMK', label: 'Myanma Kyat' },
  { code: 'MNT', label: 'Mongolian Tugrik' },
  { code: 'MOP', label: 'Macanese Pataca' },
  { code: 'MRO', label: 'Mauritanian Ouguiya' },
  { code: 'MUR', label: 'Mauritian Rupee' },
  { code: 'MVR', label: 'Maldivian Rufiyaa' },
  { code: 'MWK', label: 'Malawian Kwacha' },
  { code: 'MXN', label: 'Mexican Peso' },
  { code: 'MYR', label: 'Malaysian Ringgit' },
  { code: 'MZN', label: 'Mozambican Metical' },
  { code: 'NAD', label: 'Namibian Dollar' },
  { code: 'NGN', label: 'Nigerian Naira' },
  { code: 'NIO', label: 'Nicaraguan Córdoba' },
  { code: 'NOK', label: 'Norwegian Krone' },
  { code: 'NPR', label: 'Nepalese Rupee' },
  { code: 'NZD', label: 'New Zealand Dollar' },
  { code: 'OMR', label: 'Omani Rial' },
  { code: 'PAB', label: 'Panamanian Balboa' },
  { code: 'PEN', label: 'Peruvian Nuevo Sol' },
  { code: 'PGK', label: 'Papua New Guinean Kina' },
  { code: 'PHP', label: 'Philippine Peso' },
  { code: 'PKR', label: 'Pakistani Rupee' },
  { code: 'PLN', label: 'Polish Zloty' },
  { code: 'PYG', label: 'Paraguayan Guarani' },
  { code: 'QAR', label: 'Qatari Rial' },
  { code: 'RON', label: 'Romanian Leu' },
  { code: 'RSD', label: 'Serbian Dinar' },
  { code: 'RUB', label: 'Russian Ruble' },
  { code: 'RWF', label: 'Rwandan Franc' },
  { code: 'SAR', label: 'Saudi Riyal' },
  { code: 'SBD', label: 'Solomon Islands Dollar' },
  { code: 'SCR', label: 'Seychellois Rupee' },
  { code: 'SDG', label: 'Sudanese Pound' },
  { code: 'SEK', label: 'Swedish Krona' },
  { code: 'SGD', label: 'Singapore Dollar' },
  { code: 'SHP', label: 'Saint Helena Pound' },
  { code: 'SOS', label: 'Somali Shilling' },
  { code: 'SRD', label: 'Surinamese Dollar' },
  { code: 'SSP', label: 'South Sudanese Pound' },
  { code: 'STD', label: 'São Tomé and Príncipe Dobra' },
  { code: 'SVC', label: 'Salvadoran Colón' },
  { code: 'SYP', label: 'Syrian Pound' },
  { code: 'SZL', label: 'Swazi Lilangeni' },
  { code: 'THB', label: 'Thai Baht' },
  { code: 'TJS', label: 'Tajikistani Somoni' },
  { code: 'TMT', label: 'Turkmenistani Manat' },
  { code: 'TND', label: 'Tunisian Dinar' },
  { code: 'TOP', label: 'Tongan Paʻanga' },
  { code: 'TRY', label: 'Turkish Lira' },
  { code: 'TTD', label: 'Trinidad and Tobago Dollar' },
  { code: 'TWD', label: 'New Taiwan Dollar' },
  { code: 'TZS', label: 'Tanzanian Shilling' },
  { code: 'UAH', label: 'Ukrainian Hryvnia' },
  { code: 'UGX', label: 'Ugandan Shilling' },
  { code: 'UYU', label: 'Uruguayan Peso' },
  { code: 'UZS', label: 'Uzbekistan Som' },
  { code: 'VEF', label: 'Venezuelan Bolívar' },
  { code: 'VND', label: 'Vietnamese Dong' },
  { code: 'VUV', label: 'Vanuatu Vatu' },
  { code: 'WST', label: 'Samoan Tala' },
  { code: 'XAF', label: 'CFA Franc BEAC' },
  { code: 'XCD', label: 'East Caribbean Dollar' },
  { code: 'XOF', label: 'CFA Franc BCEAO' },
  { code: 'XPF', label: 'CFP Franc' },
  { code: 'YER', label: 'Yemeni Rial' },
  { code: 'ZAR', label: 'South African Rand' },
  { code: 'ZMW', label: 'Zambian Kwacha' },
  { code: 'ZWD', label: 'Zimbabwean Dollar' },
];

/* -------------------------------------------------------------------------- */
/* TIMEZONES                                 */
/* -------------------------------------------------------------------------- */

export const TIMEZONES = [
  { id: 'GMT', label: 'GMT - Greenwich Mean Time' },
  { id: 'Europe/London', label: '(GMT+00:00) London' },
  { id: 'Europe/Paris', label: '(GMT+01:00) Paris' },
  { id: 'Europe/Berlin', label: '(GMT+01:00) Berlin' },
  { id: 'Europe/Rome', label: '(GMT+01:00) Rome' },
  { id: 'Europe/Madrid', label: '(GMT+01:00) Madrid' },
  { id: 'Europe/Vienna', label: '(GMT+01:00) Vienna' },
  { id: 'Europe/Amsterdam', label: '(GMT+01:00) Amsterdam' },
  { id: 'Europe/Athens', label: '(GMT+02:00) Athens' },
  { id: 'Europe/Istanbul', label: '(GMT+03:00) Istanbul' },
  { id: 'Europe/Moscow', label: '(GMT+03:00) Moscow' },
  
  { id: 'America/New_York', label: '(GMT-05:00) Eastern Time (US & Canada)' },
  { id: 'America/Chicago', label: '(GMT-06:00) Central Time (US & Canada)' },
  { id: 'America/Denver', label: '(GMT-07:00) Mountain Time (US & Canada)' },
  { id: 'America/Los_Angeles', label: '(GMT-08:00) Pacific Time (US & Canada)' },
  { id: 'America/Anchorage', label: '(GMT-09:00) Alaska' },
  { id: 'Pacific/Honolulu', label: '(GMT-10:00) Hawaii' },
  { id: 'America/Sao_Paulo', label: '(GMT-03:00) Sao Paulo' },
  { id: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Buenos Aires' },
  
  { id: 'Asia/Dubai', label: '(GMT+04:00) Dubai' },
  { id: 'Asia/Kabul', label: '(GMT+04:30) Kabul' },
  { id: 'Asia/Karachi', label: '(GMT+05:00) Karachi' },
  { id: 'Asia/Kolkata', label: '(GMT+05:30) India Standard Time' },
  { id: 'Asia/Kathmandu', label: '(GMT+05:45) Kathmandu' },
  { id: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka' },
  { id: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok' },
  { id: 'Asia/Jakarta', label: '(GMT+07:00) Jakarta' },
  { id: 'Asia/Singapore', label: '(GMT+08:00) Singapore' },
  { id: 'Asia/Hong_Kong', label: '(GMT+08:00) Hong Kong' },
  { id: 'Asia/Shanghai', label: '(GMT+08:00) Beijing' },
  { id: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo' },
  { id: 'Asia/Seoul', label: '(GMT+09:00) Seoul' },
  
  { id: 'Australia/Sydney', label: '(GMT+10:00) Sydney' },
  { id: 'Australia/Adelaide', label: '(GMT+09:30) Adelaide' },
  { id: 'Australia/Perth', label: '(GMT+08:00) Perth' },
  { id: 'Pacific/Auckland', label: '(GMT+12:00) Auckland' },
  { id: 'Pacific/Fiji', label: '(GMT+12:00) Fiji' },
  
  { id: 'Africa/Cairo', label: '(GMT+02:00) Cairo' },
  { id: 'Africa/Johannesburg', label: '(GMT+02:00) Johannesburg' },
  { id: 'Africa/Lagos', label: '(GMT+01:00) Lagos' },
  { id: 'Africa/Nairobi', label: '(GMT+03:00) Nairobi' }
];