export const MEAL_PLAN_OPTIONS = [
  { id: "1", name: "All inclusive" },
  { id: "2", name: "Breakfast" },
  { id: "3", name: "Lunch" },
  { id: "4", name: "Dinner" },
  { id: "5", name: "American" },
  { id: "6", name: "Bed & breakfast" },
  { id: "7", name: "Buffet breakfast" },
  { id: "8", name: "Caribbean breakfast" },
  { id: "9", name: "Continental breakfast" },
  { id: "10", name: "English breakfast" },
  { id: "11", name: "European plan" },
  { id: "12", name: "Family plan" },
  { id: "13", name: "Full board" },
  { id: "14", name: "Half board/modified American plan" },
  { id: "15", name: "Room only (Default)" },
  { id: "16", name: "Self catering" },
  { id: "17", name: "Bermuda" },
  { id: "18", name: "Dinner bed and breakfast plan" },
  { id: "19", name: "Family American" },
  { id: "20", name: "Modified" },
  { id: "21", name: "Breakfast & lunch" },
  { id: "22", name: "Full breakfast" }
];